jobsPy/jobseekers/urls.py
from django.urls import path, include

from jobsPy.jobseekers.views import JobSeekerDashboard, EditProfile, FavouriteJobs, ApplyJobs, JobSeekerDetails, \
    AllEmployees, AddEducation, AddWorkExperience, EditEducation, EditWorkExperience, JobSeekerDeleteView, \
    ProfileDeletedView, DeleteEducation, DeleteWorkExperience
from jobsPy.notifications.views import JobSeekerNotificationListView, MarkNotificationAsReadView
from rest_framework.routers import DefaultRouter
from .views import JobSeekerViewSet

router = DefaultRouter()
router.register(r'jobseekers', JobSeekerViewSet)

urlpatterns = [
    path("all/", AllEmployees.as_view(), name="all-employees"),
    path("dashboard/", JobSeekerDashboard.as_view(), name="job seeker dashboard"),
    # path("edit-profile/<int:pk>/", EditProfile.as_view(), name="edit-profile"),
    path("edit-profile/", EditProfile.as_view(), name="edit-profile"),
    path("details/<int:pk>/", JobSeekerDetails.as_view(), name="jobseeker details"),
    path("add-education/<int:pk>/", AddEducation.as_view(), name="add-education"),
    path("edit-education/<int:pk>/", EditEducation.as_view(), name="edit-education"),
    path("add-work-experience/<int:pk>/", AddWorkExperience.as_view(), name="add-work-experience"),
    path("edit-work-experience/<int:pk>/", EditWorkExperience.as_view(), name="edit-work-experience"),
    path("favourite-jobs/", FavouriteJobs.as_view(), name="favourite_jobs"),
    path("apply-jobs/", ApplyJobs.as_view(), name="jobs-apply"),
    path('delete/', JobSeekerDeleteView.as_view(), name='delete_profile'),
    path('deleted/', ProfileDeletedView.as_view(), name='deleted_success'),
    path('delete-education/<int:pk>', DeleteEducation.as_view(), name='delete education'),
    path('delete-experience/<int:pk>', DeleteWorkExperience.as_view(), name='delete work experience'),
    path('notifications/', JobSeekerNotificationListView.as_view(), name='job seeker notifications'),
    path('notifications/<int:pk>/mark_as_read/', MarkNotificationAsReadView.as_view(), name='mark_as_read_job_seeker'),
    path('', include(router.urls)),

]

jobsPy/notifications/urls.py
from django.urls import path


urlpatterns = [
]

jobsPy/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from jobsPy.main.views import Contact, ContactFrom, NewsletterCreateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsPy.main.urls')),
    path('accounts/', include('jobsPy.accounts.urls')),
    path('jobseeker/', include('jobsPy.jobseekers.urls')),
    path('company/', include('jobsPy.company.urls')),
    path('jobs/', include('jobsPy.jobs.urls')),
    path('contact/', ContactFrom.as_view(), name="contact"),
    path('newsletter/', NewsletterCreateView.as_view(), name="newsletter"),
    path('api2/', include('jobsPy.blog.api.urls')),
    path('blog/', include('jobsPy.blog.urls')),
    path('notifications/', include('jobsPy.notifications.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('jobsPy.api.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

handler403 = 'jobsPy.main.views.custom_403'

jobsPy/jobs/models.py
from ckeditor.fields import RichTextField
from cloudinary.models import CloudinaryField
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.text import slugify

from jobsPy.jobs.validators import validate_deadline_after_today
from jobsPy.main.models import Seniority

# Create your models here.

UserModel = get_user_model()


class Skills(models.Model):
    name = models.CharField(blank=True, null=True, max_length=20)

    def __str__(self):
        return self.name


def unique_slugify(instance, slug):
    model = instance.__class__
    unique_slug = slug
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slug + get_random_string(length=5)
    return unique_slug


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)


JOB_TYPE = (
    ('fulltime', "Full time"),
    ('parttime', "Part time"),
    ('remote', "Remote"),
    ('internship', "Internship"),
)


class Job(models.Model):
    user = models.ForeignKey(UserModel,  on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True)
    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    seniority = models.ForeignKey(Seniority, on_delete=models.SET_NULL, blank=True, null=True)
    description = RichTextField(null=False, blank=False)
    responsibilities = RichTextField(null=False, blank=False)
    benefits = RichTextField(null=True, blank=True)
    # job_image = models.ImageField(null=True, blank=True, upload_to="jobs/image", default="images/default/default.jpg")
    job_image = CloudinaryField('image', blank=True, null=True)
    vacancy = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=300,)
    job_type = models.CharField(choices=JOB_TYPE, max_length=10)
    salary = models.CharField(max_length=30, blank=True)
    deadline = models.DateField(
        validators=[validate_deadline_after_today]
    )
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    needed_skills = models.ManyToManyField(Skills, related_name="needed_skills")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']


class FavoriteJob(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'job')  # Ensure a job can be favorited only once per user


class Applicant(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applicants")
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)
    status = models.SmallIntegerField(default=1)

    class Meta:
        ordering = ["id"]
        unique_together = ["user", "job"]

    @property
    def get_status(self):
        if self.status == 1:
            return "Pending"
        elif self.status == 2:
            return "Accepted"
        else:
            return "Rejected"

jobsPy/jobseekers/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView, View
from jobsPy.core.accounts_mixins import JobSeekerRequiredMixin, JobSeekerOwnerRequiredMixin, JobEditMixin
from jobsPy.jobs.models import FavoriteJob, Applicant, Skills
from jobsPy.jobseekers.forms import EditProfileFrom, EducationForm, WrokExperienceForm
from jobsPy.jobseekers.models import JobSeeker, Education, Experience
from jobsPy.notifications.models import NotificationJobSeeker
from rest_framework import viewsets, permissions
from .models import JobSeeker
from .serializers import JobSeekerSerializer

userModel = get_user_model()
# Create your views here.


class JobSeekerDashboard(LoginRequiredMixin, JobSeekerRequiredMixin, TemplateView):
    template_name = "job_seekers/jobseeker_dashboard.html"

    def get_context_data(self, **kwargs):

        all_favourite = FavoriteJob.objects.filter(user_id=self.request.user.pk).count()
        all_jobs_apply = Applicant.objects.filter(user_id=self.request.user.pk).count()
        all_jobs_pending = Applicant.objects.filter(user_id=self.request.user.pk).filter(status=1).count()
        all_jobs_accepted = Applicant.objects.filter(user_id=self.request.user.pk).filter(status=2).count()
        all_jobs_rejected = Applicant.objects.filter(user_id=self.request.user.pk).filter(status=3).count()


#         job_creator_jobs = Job.objects.filter(user=self.request.user)
#         all_favourite = FavoriteJob.objects.filter(job__in=job_creator_jobs).count()
#         user_jobs = Job.objects.filter(user=self.request.user)
#
#         job_count = FavoriteJob.objects.filter(job__in=job_creator_jobs).count()
#
#         job_for_this_user = Job.objects.filter(user=self.request.user, is_published=True)
#
#
# # ChatGPT get all applicant for current logged user
#         all_applicant = (
#             Applicant.objects.filter(job__user=self.request.user, job__is_published=True)
#             .values('user')
#             .count()
#         )
#
        context = super().get_context_data(**kwargs)
#         context['user_jobs'] = user_jobs
#         context['job_count'] = job_count
        context['all_favourite'] = all_favourite
        context['all_jobs_apply'] = all_jobs_apply
        context['all_jobs_pending'] = all_jobs_pending
        context['all_jobs_rejected'] = all_jobs_rejected
        context['all_jobs_accepted'] = all_jobs_accepted
        return context


class AllEmployees(ListView):
    model = JobSeeker
    template_name = "job_seekers/all_jobseekers.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(activated=True)
        city = self.request.GET.get('city')
        if city:
            queryset = queryset.filter(city__icontains=city)
        skill_name = self.request.GET.get('skill')
        if skill_name:
            queryset = queryset.filter(skills__name=skill_name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['skills'] = Skills.objects.all()
        return context

    # def get_queryset(self):
    #     # Use prefetch_related to fetch all related languages for each JobSeeker
    #     print(JobSeeker.objects.prefetch_related('languages').all())
    #     return JobSeeker.objects.prefetch_related('languages').all()


class JobSeekerDetails(DetailView):
    model = JobSeeker
    template_name = "job_seekers/job_seekers_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['skills'] = Skills.objects.all()
        return context


class EditProfile(LoginRequiredMixin, UpdateView):
    model = JobSeeker
    template_name = "job_seekers/edit_profile.html"
    form_class = EditProfileFrom
    success_url = reverse_lazy("job seeker dashboard")

    def get_object(self, queryset=None):
        # Get the JobSeeker instance associated with the current logged-in user
        return self.request.user.jobseeker


class FavouriteJobs(LoginRequiredMixin, JobSeekerRequiredMixin, ListView):
    template_name = "job_seekers/favourite_jobs.html"

    def get_queryset(self):
        return FavoriteJob.objects.filter(user=self.request.user).select_related('job')


class ApplyJobs(LoginRequiredMixin, JobSeekerRequiredMixin, ListView):
    template_name = "job_seekers/apply-jobs.html"

    def get_queryset(self):
        return Applicant.objects.filter(user_id=self.request.user.pk).all()


class AddEducation(CreateView):
    model = Education
    template_name = "job_seekers/add_education.html"
    form_class = EducationForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        jobseeker_pk = self.kwargs['pk']
        jobseeker = get_object_or_404(JobSeeker, pk=jobseeker_pk)
        # Set the job_seeker field and save the form
        form.instance.job_seeker = jobseeker
        return super().form_valid(form)

    def get_success_url(self):
        # return reverse_lazy('edit-profile', kwargs={'pk': self.kwargs['pk']})
        return reverse_lazy('job seeker dashboard')


class EditEducation(LoginRequiredMixin, JobSeekerRequiredMixin, JobEditMixin, UpdateView):
    model = Education
    template_name = "job_seekers/edit_education.html"
    form_class = EducationForm

    def get_success_url(self):
        # return reverse_lazy('edit-profile', kwargs={'pk': self.kwargs['pk']})
        return reverse_lazy('job seeker dashboard')


class DeleteEducation(LoginRequiredMixin, JobSeekerRequiredMixin, JobEditMixin, DeleteView):
    model = Education
    template_name = "job_seekers/delete_education.html"
    success_url = reverse_lazy('job seeker dashboard')


class AddWorkExperience(CreateView):
    # model = Experience
    template_name = "job_seekers/add_work_experience.html"
    form_class = WrokExperienceForm

    def form_valid(self, form):
        jobseeker_pk = self.kwargs['pk']
        jobseeker = get_object_or_404(JobSeeker, pk=jobseeker_pk)
        # Set the job_seeker field and save the form
        form.instance.job_seeker = jobseeker
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('job seeker dashboard')


class EditWorkExperience(JobSeekerRequiredMixin, JobEditMixin, UpdateView):
    model = Experience
    template_name = "job_seekers/edit_edit_work_experience.html"
    form_class = WrokExperienceForm

    def get_success_url(self):
        # return reverse_lazy('edit-profile', kwargs={'pk': self.kwargs['pk']})
        return reverse_lazy('job seeker dashboard')


class DeleteWorkExperience(LoginRequiredMixin, JobSeekerRequiredMixin, JobEditMixin, DeleteView):
    model = Experience
    template_name = "job_seekers/delete_experience.html"
    success_url = reverse_lazy('job seeker dashboard')


class JobSeekerDeleteView(LoginRequiredMixin, JobSeekerRequiredMixin, DeleteView):
    model = userModel
    template_name = "job_seekers/delete_profile.html"
    success_url = reverse_lazy('deleted_success')

    def get_object(self, queryset=None):
        return self.request.user


class ProfileDeletedView(TemplateView):
    template_name = "job_seekers/profile_deleted.html"


class JobSeekerViewSet(viewsets.ModelViewSet):
    queryset = JobSeeker.objects.filter(activated=True)
    serializer_class = JobSeekerSerializer
    permission_classes = permissions.AllowAny,
    pagination_class = None  # Disable pagination

    def get_queryset(self):
        queryset = JobSeeker.objects.filter(activated=True)
        city = self.request.query_params.get('city', None)
        if city:
            queryset = queryset.filter(city=city)
        return queryset

jobsPy/notifications/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, View

from jobsPy.notifications.models import NotificationJobSeeker, Notification


class JobSeekerNotificationListView(LoginRequiredMixin, ListView):
    model = NotificationJobSeeker
    template_name = 'job_seekers/notifications.html'
    context_object_name = 'notifications'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class MarkNotificationAsReadView(View):
    def get(self, request, *args, **kwargs):
        notification_id = self.kwargs['pk']
        notification = NotificationJobSeeker.objects.get(pk=notification_id)
        notification.is_read = not notification.is_read
        notification.save()
        return redirect('job seeker notifications')



class CompanyNotificationListView(LoginRequiredMixin, ListView):
    model = Notification
    template_name = 'company/notifications.html'
    context_object_name = 'notifications'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class MarkCompanyNotificationAsReadView(View):
    def get(self, request, *args, **kwargs):
        notification_id = self.kwargs['pk']
        notification = Notification.objects.get(pk=notification_id)
        notification.is_read = not notification.is_read
        notification.save()
        return redirect('company-notifications')

templates/job_seekers/add_work_experience.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Add Work Experience {% endblock %}
{% block main_content %}
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Add work experience</h1>
                        <p>Business plan draws on a wide range of knowledge from different business<br> disciplines.
                            Business draws on a wide range of different business .</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Add Work Experience</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Main Content Start -->
    <div class="change-password section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    <!-- Start Main Content -->

                    {% include "job_seekers/job_seeker_menu.html" %}

                    <!-- End Main Content -->
                    <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Add Work Experience</h3>
                            <p>Here you can add work experience.</p>
                             {% if form.errors %}
                            <div class="alert alert-danger">
                            {{ form.errors }}
                            </div>
                            {% endif %}
                            
                
                            <form method="post" action="{% url 'add-work-experience' user.jobseeker.pk %}" enctype="multipart/form-data">
                                <div class="row">
                                    {{ form.media }}
                              {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        {{ field }}
                     </div>
                        {% for error in field.errors %}
                          <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                                    {% csrf_token %}
                                    <div class="col-lg-12">
                                        <div class="button">
                                            <button class="btn">Add Work Experience</button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content end -->

    
    
 {% endblock %}

templates/job_seekers/all_jobseekers.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All Jobseekrs - JobsPy {% endblock %}
{% block main_content %}

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Job Seekers</h1>
                        <p>Find employees that match your hiring criteria.</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Job Seekers</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Main Content Start -->
    <div class="manage-resumes section">
        <div class="container">
            <div class="resume-inner">
                <div class="row">

                    <div class="col-lg-8 col-12">

                        <div class="inner-content">
                            <!-- Start Resume Item -->
                            {% for jobseeker in object_list %}
                            <div class="resume-item">
                            {% if jobseeker.profile_picture %}
                                <img src="{{ jobseeker.profile_picture.url}}" alt="Candidate">
                                {% else %}
                                       <img src="{% static 'images/clients/default_profile.png' %}" alt="Candidate">
                                {% endif %}
                                <div class="right">
                                    <h3>
                                        <a href="{% url 'jobseeker details' jobseeker.pk %}">{{ jobseeker.first_name}} {{ jobseeker.last_name }}</a>
                                    </h3>
                                    <span class="deg">{{ jobseeker.occupation}}</span>
                                    <ul class="experience">
                                        {% if jobseeker.seniority %}
                                        <li>Seniority: <span>{{ jobseeker.seniority }}</span></li>
                                            {% else %}
                                            <li>Seniority: <span></span></li>
                                        {% endif %}
                                    {% if jobseeker.github %}
                                        <li>GitHub: <span><a target="_blank" href="{{ jobseeker.github }}" target="_blank>">Link</a></span></li>
                    {% else %}
                                        <li>GitHub: </li>
                                                    {% endif %}
                                        <li>
                                            <i class="lni lni-map-marker"></i>
                                            {{ jobseeker.city}}
                                        </li>
                                    </ul>
                                    <ul class="skills">

                                        {% for skill in jobseeker.skills.all %}
                                        <li>{{ skill.name }}</li>

                                            {% endfor %}
                                    </ul>

                                </div>
                            </div>
                            {% endfor %}
                            <!-- End Resume Item -->


                        </div>
                        <!-- Pagination -->
                    {% if is_paginated %}
    <div class="pagination left pagination-md-center">
        <ul class="pagination-list">
            {% if page_obj.has_previous %}
{#                <li><a href="?page=1"><i class="lni lni-arrow-left"></i></a></li>#}
                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="lni lni-arrow-left"></i></a></li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                <li {% if page_obj.number == num %}class="active"{% endif %}><a href="?page={{ num }}">{{ num }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}"><i class="lni lni-arrow-right"></i></a></li>
{#                <li><a href="?page={{ page_obj.paginator.num_pages }}"><i class="lni lni-arrow-right"></i></a></li>#}
            {% endif %}
        </ul>
    </div>
{% endif %}
                        <!-- End Pagination -->
                    </div>
                {% include 'job_seekers/aside.html' %}
                </div>
            </div>
        </div>
    </div>

    <!-- Main Content end -->
{% endblock  %}

templates/job_seekers/aside.html
{% load static %}
<aside class="col-lg-4 col-md-12 col-12">
                    <div class="sidebar">
                            <div class="widget search-widget">
{#                            <h5 class="widget-title"><span>Search This Site</span></h5>#}
                             <form method="get" action="{% url 'all-employees' %}">
                                <input type="text" name="city" placeholder="Search by city...">
                                <button type="submit"><i class="lni lni-search-alt"></i></button>
                            </form>
                        </div>
                        <div class="widget popular-tag-widget">
                            <h5 class="widget-title"><span>Popular Skills</span></h5>
                            <div class="tags">
                                  {% for skill in skills %}
                                    <a href={% url 'all-employees' %}?skill={{ skill.name}}>{{ skill.name }}</a>
                                  {% endfor %}

                            </div>
                        </div>
{#                        {% include "jobs/category_slide.html" %}#}


                        <div class="widget popular-feeds">
                            <h5 class="widget-title"><span>Latest Blog Posts with DRF</span></h5>

                            <div class="popular-feed-loop">

                            </div>
                        </div>


                    </div>
                </aside>


        <script src="{% static '/js/blog/popular_feeds.js' %}"></script>

templates/job_seekers/delete_education.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Delete Education - JobsPy {% endblock %}
{% block main_content %}
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Delete  Profile</h1>
                        <p>Editing and updating a profile allows you to keep information current and accurate,<br>
while also allowing companies to find you</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'job seeker dashboard' %}">Dashboard</a></li>
                        <li>Delete Education</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Main Content Start -->
    <div class="change-password section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    <!-- Start Main Content -->

                    {% include "job_seekers/job_seeker_menu.html" %}

                    <!-- End Main Content -->
                    <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Delete Education</h3>
                            <p>Here you can delete your education.</p>

                            <form method="post">
                                <div class="row">
                                    {{ form }}


                                    {% csrf_token %}
                                    <div class="col-lg-12">
                                        <div class="button">
                                            <button class="btn">Delete</button>
                                           <a style="margin-left: 20px" class="btn" href="{% url 'job seeker dashboard' %}">Cancel</a>  <!-- Redirect to profile page if cancel -->
                                        </div>
    
                                    </div>
                                </div>

                            </form>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content end -->

 {% endblock %}

templates/job_seekers/job_seeker_menu.html
                {% load notification_tags %}
                    <div class="col-lg-4 col-12">
                        <div class="dashbord-sidebar">
                            <ul>
                                <li class="heading">Manage Account</li>
                                <li><a class="{% if request.resolver_match.url_name == 'job seeker dashboard' %}active{% endif %}"  href="{% url 'job seeker dashboard' %}"><i class="lni lni-clipboard"></i> Dashboard</a></li>
                                <li><a class="{% if request.resolver_match.url_name == 'edit-profile' %}active{% endif %}"  href="{% url 'edit-profile' %}"><i class="lni lni-clipboard"></i> Edit Profile </a></li>
                                <li><a class="{% if request.resolver_match.url_name == 'favourite_jobs' %}active{% endif %}"  href="{% url 'favourite_jobs' %}"><i class="lni lni-clipboard"></i> Bookmarked Jobs <span class="notifi">{{ user.favoritejob_set.all|length}}</span></a></li>
                                <li><a class="{% if request.resolver_match.url_name == 'jobs-apply' %}active{% endif %}" href="{% url 'jobs-apply' %}"><i class="lni lni-alarm"></i>Job Applications <span class="notifi">{{ user.jobseeker.get_user_all_applicant}}</span></a></li>
               
                                 {% if 'main.add_newsletter' in perms %}
                                <li><a class="{% if request.resolver_match.url_name == 'newsletter' %}active{% endif %}" href="{% url 'newsletter' %}"><i class="lni lni-alarm"></i>Send Newsletter </a></li>
                               {% endif %}
                                <li><a  href="{% url 'job seeker notifications' %}"><i class="lni lni-alarm"></i> Notifications <span class="notifi">{{ request.user|unread_notifications  }}</span></a></li>
                                <li><a class="{% if request.resolver_match.url_name == 'change-password' %}active{% endif %}" href="{% url 'change-password' %}"><i class="lni lni-lock"></i> Change Password</a></li>
                                <li><a class="{% if request.resolver_match.url_name == 'delete_profile' %}active{% endif %}" style="color:red" href="{% url 'delete_profile' %}"><i class="lni lni-lock"></i> Delete Profile</a></li>
                                <li><a href="{% url 'sing-out' %}"><i class="lni lni-upload"></i> Sign Out</a></li>
                            </ul>
                        </div>
                    </div>