jobsPy/blog/api/urls.py
from django.urls import path

from jobsPy.blog.views import BlogPostListCreateAPIView, BlogPostRetrieveUpdateDestroyAPIView, CommentListCreateAPIView, \
    CommentRetrieveUpdateDestroyAPIView, LatestBlogPostsAPIView

urlpatterns = [
    path('blog/<int:pk>/', BlogPostRetrieveUpdateDestroyAPIView.as_view(), name='blog-detail'),
    path('blog/<int:pk>/comments/', CommentListCreateAPIView.as_view(), name='comment-list'),
    path('blog/<int:pk>/comments/<int:comment_pk>/', CommentRetrieveUpdateDestroyAPIView.as_view(), name='comment-detail'),
    path('blog/last/', LatestBlogPostsAPIView.as_view(), name='last-5-blogs'),
]

jobsPy/blog/urls.py
from django.urls import path

from jobsPy.blog.views import BlogList, SingleBlog, CreateBlog, LatestBlogPostsAPIView

urlpatterns = [
    # path('blog/', BlogPostListCreateAPIView.as_view(), name='blog-list'),
    # path('blog/<int:pk>/', BlogPostRetrieveUpdateDestroyAPIView.as_view(), name='blog-detail'),
    path('', BlogList.as_view(), name='blog-list'),
    path('<int:pk>/', SingleBlog.as_view(), name='blog-detail'),
    path('add/', CreateBlog.as_view(), name='blog-create'),
    # Other URL patterns...
]

jobsPy/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from jobsPy.main.views import Contact, ContactFrom, NewsletterCreateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsPy.main.urls')),
    path('accounts/', include('jobsPy.accounts.urls')),
    path('jobseeker/', include('jobsPy.jobseekers.urls')),
    path('company/', include('jobsPy.company.urls')),
    path('jobs/', include('jobsPy.jobs.urls')),
    path('contact/', ContactFrom.as_view(), name="contact"),
    path('newsletter/', NewsletterCreateView.as_view(), name="newsletter"),
    path('api2/', include('jobsPy.blog.api.urls')),
    path('blog/', include('jobsPy.blog.urls')),
    path('notifications/', include('jobsPy.notifications.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('jobsPy.api.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

handler403 = 'jobsPy.main.views.custom_403'

jobsPy/blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models

from jobsPy.jobseekers.models import JobSeeker

userModel = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=2000, null=False, blank=False)
    description = RichTextField(null=False, blank=False)
    more_info = RichTextField(null=False, blank=False)
    image_url_1 = models.URLField(null=False, blank=False)
    image_url_2 = models.URLField(null=False, blank=False)
    image_url_3 = models.URLField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    views = models.IntegerField(default=0)
    author = models.ForeignKey(JobSeeker, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(userModel, on_delete=models.CASCADE)
    content = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

jobsPy/jobs/models.py
from ckeditor.fields import RichTextField
from cloudinary.models import CloudinaryField
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.text import slugify

from jobsPy.jobs.validators import validate_deadline_after_today
from jobsPy.main.models import Seniority

# Create your models here.

UserModel = get_user_model()


class Skills(models.Model):
    name = models.CharField(blank=True, null=True, max_length=20)

    def __str__(self):
        return self.name


def unique_slugify(instance, slug):
    model = instance.__class__
    unique_slug = slug
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slug + get_random_string(length=5)
    return unique_slug


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)


JOB_TYPE = (
    ('fulltime', "Full time"),
    ('parttime', "Part time"),
    ('remote', "Remote"),
    ('internship', "Internship"),
)


class Job(models.Model):
    user = models.ForeignKey(UserModel,  on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True)
    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    seniority = models.ForeignKey(Seniority, on_delete=models.SET_NULL, blank=True, null=True)
    description = RichTextField(null=False, blank=False)
    responsibilities = RichTextField(null=False, blank=False)
    benefits = RichTextField(null=True, blank=True)
    # job_image = models.ImageField(null=True, blank=True, upload_to="jobs/image", default="images/default/default.jpg")
    job_image = CloudinaryField('image', blank=True, null=True)
    vacancy = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=300,)
    job_type = models.CharField(choices=JOB_TYPE, max_length=10)
    salary = models.CharField(max_length=30, blank=True)
    deadline = models.DateField(
        validators=[validate_deadline_after_today]
    )
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    needed_skills = models.ManyToManyField(Skills, related_name="needed_skills")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']


class FavoriteJob(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'job')  # Ensure a job can be favorited only once per user


class Applicant(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applicants")
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)
    status = models.SmallIntegerField(default=1)

    class Meta:
        ordering = ["id"]
        unique_together = ["user", "job"]

    @property
    def get_status(self):
        if self.status == 1:
            return "Pending"
        elif self.status == 2:
            return "Accepted"
        else:
            return "Rejected"

jobsPy/blog/views.py
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from rest_framework import generics, permissions, pagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from jobsPy.accounts.forms import LoginForm
from jobsPy.blog.models import BlogPost, Comment
from jobsPy.blog.permission import IsAuthor, IsAuthorOrReadOnly
from jobsPy.blog.serializers import BlogPostSerializer, CommentSerializer, CommentSerializerCreate
from jobsPy.core.accounts_mixins import AuthorRequiredMixin


# Create your views here.
class BlogPostPagination(pagination.PageNumberPagination):
    page_size = 10  # Set the number of items per page
    page_size_query_param = 'page_size'
    max_page_size = 1000  # Optionally, set a maximum page size


class BlogPostListCreateAPIView(generics.ListCreateAPIView):
    queryset = BlogPost.objects.all()
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    serializer_class = BlogPostSerializer
    pagination_class = BlogPostPagination

    def perform_create(self, serializer):
        serializer.save(author=self.request.user.jobseeker)

    def get_permissions(self):
        if self.request.method == 'POST':
            return [IsAuthor()]
        return super().get_permissions()


class BlogPostRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = BlogPost.objects.all()
    serializer_class = BlogPostSerializer
    permission_classes = [IsAuthorOrReadOnly]

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.views += 1
        instance.save()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)


class BlogList(TemplateView):
    template_name = 'blog/blogs.html'


class SingleBlog(TemplateView, LoginView):
    template_name = 'blog/single-blogs.html'
    form_class = LoginForm


class CreateBlog(AuthorRequiredMixin, TemplateView):
    template_name = 'blog/create-blog.html'
    permission_classes = [IsAuthor()]


class CommentListCreateAPIView(generics.ListCreateAPIView):
    queryset = Comment.objects.all()

    def get_queryset(self):
        post_id = self.kwargs.get('pk')
        return Comment.objects.filter(post_id=post_id)

    def perform_create(self, serializer):
        post_id = self.kwargs.get('pk')
        blog_post = BlogPost.objects.get(pk=post_id)
        serializer.save(author=self.request.user, post=blog_post)

    def get_serializer_class(self):

        if self.request.method == 'POST':
            return CommentSerializerCreate
        return CommentSerializer


class CommentRetrieveUpdateDestroyAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get_object(self):
        # Retrieve the comment ID from the URL parameters
        comment_id = self.kwargs.get('comment_pk')

        return Comment.objects.get(pk=comment_id)


class LatestBlogPostsAPIView(generics.ListAPIView):
    queryset = BlogPost.objects.all().order_by('-created_at')[:5]
    serializer_class = BlogPostSerializer

templates/blog/blogs.html
{% extends 'base.html' %}      
{% load static %}
{% block title %} Blogs - JobsPy{% endblock %}
{% block main_content %}


    <!-- End Header Area -->

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">News and blogs / Django Rest Framework</h1>
                        <p>First steps in Django Rest Framework<br> </p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Blogs</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Start Blog Singel Area -->
    <section class="section latest-news-area blog-list">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-7 col-12">
                    <div id="blog-list" class="row">


                    </div>
                    <!-- Pagination -->
                    <div class="pagination center">
                        <ul class="pagination-list">
                            <li><a href="#"><i class="lni lni-chevron-left"></i></a></li>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#"><i class="lni lni-chevron-right"></i></a></li>
                        </ul>
                    </div>
                    <!--/ End Pagination -->
                </div>
                <aside class="col-lg-4 col-md-5 col-12">
                    <div class="sidebar">
                    
                                  {% if 'blog.add_blogpost' in perms %}
                                <div class="sidebar-widget">
                                <div class="inner">
                            <div class="row m-n2 button">
                                        <div class=" col-lg-12  ">
                                            <a href="{% url 'blog-create' %}" class="d-block btn"><i class="fa fa-heart-o mr-1"></i> Add Blog Post</a>
                                        </div>
                                     </div>
                                </div>
                            </div>

                    {% endif %}
                        <div class="widget search-widget">
                            <h5 class="widget-title"><span>Search ...</span></h5>
                            <form action="#">
                                <input type="text" placeholder="Search Here...">
                                <button type="submit"><i class="lni lni-search-alt"></i></button>
                            </form>
                        </div>
                        <div class="widget popular-feeds">
                            <h5 class="widget-title"><span>Popular Feeds</span></h5>

                        </div>
                        <div class="widget categories-widget">
                            <h5 class="widget-title"><span>Categories</span></h5>
{#                            <ul class="custom">#}
{#                                <li>#}
{#                                    <a href="#">Announcement<span>26</span></a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#">Indeed Events<span>30</span></a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#">Tips & Tricks<span>71</span></a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#">Experiences<span>56</span></a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#">Case Studies<span>15</span></a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#">Labor Market News<span>12</span></a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a href="#">HR Best Practices<span>17</span></a>#}
{#                                </li>#}
{#                            </ul>#}
                        </div>
                        <div class="widget popular-tag-widget">
                            <h5 class="widget-title"><span>Popular Tags</span></h5>
{#                            <div class="tags">#}
{#                                <a href="#">Jobpress</a>#}
{#                                <a href="#">Design</a>#}
{#                                <a href="#">HR</a>#}
{#                                <a href="#">Recruiter</a>#}
{#                                <a href="#">Interview</a>#}
{#                                <a href="#">Employee</a>#}
{#                                <a href="#">Labor</a>#}
{#                                <a href="#">Salary</a>#}
{#                                <a href="#">Consult</a>#}
{#                                <a href="#">Business</a>#}
{#                                <a href="#">Candidates</a>#}
{#                            </div>#}
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </section>
     <script src="{% static 'js/blog/blog.js' %}"></script>
  {% endblock %}

templates/blog/create-blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Blogs - JobsPy{% endblock %}
{% block main_content %}

    <!-- End Header Area -->

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">News and blogs / Django Rest Framework</h1>
                        <p>First steps in Django Rest Framework<br> </p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="index.html">Home</a></li>
                        <li><a href="#">Blog</a></li>
                        <li>Blog Grid Sidebar</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Start Blog Singel Area -->
    <section class="section latest-news-area blog-list">
        <div class="container">
            <div class="row">

                       <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Add New Blog Post</h3>
                            <p>Here you can add new blog post.</p>



                            <form id="blog-post-form">
                                <div class="row">

                    <div class="form-group">

                    <span><label for="id_title" class="required">Title:</label></span>

                    <input type="text" name="title" value="" maxlength="200" class="form-control" required="" id="id_title">
                     </div>



                    <div class="form-group">

                    <span><label for="id_description" class="required">Description:</label></span>

                    <textarea name="description" cols="40" rows="10" class="form-control" required="" id="id_description"></textarea>
                     </div>


                    <div class="form-group">

                        <label class="required" for="id_image_url_1">Main Image:</label>

                    <input type="text" name="image_url_1" value="" maxlength="200" class="form-control" id="id_image_url_1">
                     </div>

                    <div class="form-group">

                        <label for="id_image_url_2">Image :</label>

                    <input type="text" name="image_url_2" value="" maxlength="200" class="form-control" id="id_image_url_2">
                     </div>
                                    
                                                        <div class="form-group">

                        <label for="id_image_url_3">Image :</label>

                    <input type="text" name="image_url_3" value="" maxlength="200" class="form-control" id="id_image_url_3">
                     </div>

                                </div>
                                
                                                    <div class="form-group">

                    <span><label for="id_more_info" class="required">More Info:</label></span>

                    <textarea name="more_info" cols="40" rows="10" class="form-control" required="" id="id_more_info"></textarea>
                     </div>

                                        <div class="button">
                                            <button class="btn">Save</button>
                                        </div>
{% csrf_token %}
                            </form>

                            <script>
                                document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('blog-post-form');

    form.addEventListener('submit', function(event) {
        event.preventDefault();  // Prevent default form submission

        const title = document.getElementById('id_title').value;
        const description = document.getElementById('id_description').value;
        const image_url_1 = document.getElementById('id_image_url_1').value;
        const image_url_2 = document.getElementById('id_image_url_2').value;
        const image_url_3 = document.getElementById('id_image_url_3').value;
        const more_info = document.getElementById('id_more_info').value;
        // Get other form field values as needed


        const data = {
            title: title,
            description: description,
            image_url_1: image_url_1,
            image_url_2: image_url_2,
            image_url_3: image_url_3,
            more_info: more_info,
            // Include other fields as needed
        };
         const csrfToken = "{{ csrf_token }}";

                 const headers = {
            'Content-Type': 'application/json',
            'X-CSRFToken': csrfToken
        };
        // Send POST request to API
        fetch('/api/blog/', {
            method: 'POST',
         headers: headers,
            body: JSON.stringify(data)

        })
        .then(response => {

            if (response.ok) {
                // Blog post created successfully
                // Redirect or show success message
                window.location.href = '{% url 'blog-list' %}';
            } else {

            }
        })
        .catch(error => {
            console.error('Error creating blog post:', error);
        });
    });
});
                            </script>

                        </div>
                    </div>
                
            </div>
        </div>
    </section>

  {% endblock %}

templates/blog/single-blogs.html
{% extends 'base.html' %}
{% block title %}  Stay informed with JobsPy {% endblock %}
{% load socialaccount %}
{% load static %}
{% block main_content %}
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Blog Single</h1>
                        <p>Business plan draws on a wide range of knowledge from different business<br> disciplines.
                            Business draws on a wide range of different business .</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Blog Single</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Start Blog Singel Area -->
    <section class="section blog-single">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1 col-12">
                    <div  id="single-post" class="single-inner">
                        <h3>Loading...</h3>
                    </div>
                    <div class="change-password">

                        <div  class="post-comments password-content">
                                         {% if user.is_authenticated %}
                            <form id="comment-form">
                                <div class="required">
    <label for="comment-content" class="required">Comment:</label>
                                    <textarea type="text" rows="5" name="comment" id="comment-content" class="form-control" placeholder="Write your comment here..."></textarea>
                            </div>
                                <div class="button">
    <button class="btn" type="submit">Post Comment</button>
                                </div>
                                {% csrf_token %}
</form>
                                             {% else %}
                                                  <div class="col-lg-6 col-md-10 col-12">
                                        <div class="login-information">

                        <form method="post" action="{% url 'login' %}">
                            <div class="row">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
                 {% for field in form %}
                    <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                     </div>
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}

                {% endfor %}
                                                <input type="hidden" value="{{request.path}}" name="next"/>


                                <div class="col-lg-12 button">
                                    <button class="btn">
                                        Login
                                    </button>
                                </div>
                            </div>
                        </form>

                </div>
                    <a class="google" href="{% provider_login_url 'google' %}">Login with Google</a>
                    <a class="github" href="{% provider_login_url 'github' %}">Login with GitHub</a>

            </div>
                                             {% endif %}

                                <h3 id="comment-number" class="comment-title"><span></span></h3>
                                <ul id="comments-list" class="comments-list">
                                </ul>
                            </div>

                    </div>
                </div>
            </div>

        </div>

    </section>
    <script>
    var CSRF_TOKEN = '{{ csrf_token }}';
</script>
       <script src="{% static '/js/blog/blog_detail.js' %}"></script>
       <script src="{% static '/js/blog/load_comment.js' %}"></script>
 {% if user.is_authenticated %}
   <script src="{% static '/js/blog/post_comment.js' %}"></script>
    {% endif %}




{% endblock %}