jobsPy/jobs/urls.py
from django.urls import path

from jobsPy.jobs.views import JobCreateView, JobDetails, EditJob, AllJobsView, \
    RemoveFromFavoritesView, add_to_favorites, apply_for_job, DeleteJob, AllJobsViewApi
from jobsPy.jobseekers.views import FavouriteJobs, ApplyJobs
from jobsPy.main.views import JobsCategory

urlpatterns = [
    path("", AllJobsView.as_view(), name="all-jobs"),
    path('create-job/', JobCreateView.as_view(), name="create_job"),
    path('edit-job/<int:pk>/', EditJob.as_view(), name="edit_job"),
    path('delete-job/<int:pk>/', DeleteJob.as_view(), name="delete job"),
    path("job-details/<int:pk>/", JobDetails.as_view(), name="job_details"),
    path("add-to-favourite/<int:pk>/", add_to_favorites, name="add-to-favourite"),
    path("remove-from-favourite/<int:pk>/", RemoveFromFavoritesView.as_view(), name="remove_From_fav"),
    path("apply_for_job/<int:pk>/", apply_for_job, name="apply_for_job"),
    path("favourite-jobs/", FavouriteJobs.as_view(), name="favourite_jobs"),
    path("apply-jobs/", ApplyJobs.as_view(), name="jobs-apply"),
    path('category/<slug:category_slug>/', JobsCategory.as_view(), name='jobs_category'),
    path('api/', AllJobsViewApi.as_view(), name='all_jobs'),


]

jobsPy/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from jobsPy.main.views import Contact, ContactFrom, NewsletterCreateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsPy.main.urls')),
    path('accounts/', include('jobsPy.accounts.urls')),
    path('jobseeker/', include('jobsPy.jobseekers.urls')),
    path('company/', include('jobsPy.company.urls')),
    path('jobs/', include('jobsPy.jobs.urls')),
    path('contact/', ContactFrom.as_view(), name="contact"),
    path('newsletter/', NewsletterCreateView.as_view(), name="newsletter"),
    path('api2/', include('jobsPy.blog.api.urls')),
    path('blog/', include('jobsPy.blog.urls')),
    path('notifications/', include('jobsPy.notifications.urls')),
    path('accounts/', include('allauth.urls')),
    path('api/', include('jobsPy.api.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#         urlpatterns += static(settings.MEDIA_URL,
#                               document_root=settings.MEDIA_ROOT)

handler403 = 'jobsPy.main.views.custom_403'

jobsPy/jobs/models.py
from ckeditor.fields import RichTextField
from cloudinary.models import CloudinaryField
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.crypto import get_random_string
from django.utils.text import slugify

from jobsPy.jobs.validators import validate_deadline_after_today
from jobsPy.main.models import Seniority

# Create your models here.

UserModel = get_user_model()


class Skills(models.Model):
    name = models.CharField(blank=True, null=True, max_length=20)

    def __str__(self):
        return self.name


def unique_slugify(instance, slug):
    model = instance.__class__
    unique_slug = slug
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slug + get_random_string(length=5)
    return unique_slug


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)


JOB_TYPE = (
    ('fulltime', "Full time"),
    ('parttime', "Part time"),
    ('remote', "Remote"),
    ('internship', "Internship"),
)


class Job(models.Model):
    user = models.ForeignKey(UserModel,  on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    slug = models.SlugField(allow_unicode=True, max_length=100, unique=True)
    category = models.ForeignKey(Category,  on_delete=models.CASCADE)
    seniority = models.ForeignKey(Seniority, on_delete=models.SET_NULL, blank=True, null=True)
    description = RichTextField(null=False, blank=False)
    responsibilities = RichTextField(null=False, blank=False)
    benefits = RichTextField(null=True, blank=True)
    # job_image = models.ImageField(null=True, blank=True, upload_to="jobs/image", default="images/default/default.jpg")
    job_image = CloudinaryField('image', blank=True, null=True)
    vacancy = models.IntegerField(null=True, blank=True)
    location = models.CharField(max_length=300,)
    job_type = models.CharField(choices=JOB_TYPE, max_length=10)
    salary = models.CharField(max_length=30, blank=True)
    deadline = models.DateField(
        validators=[validate_deadline_after_today]
    )
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    needed_skills = models.ManyToManyField(Skills, related_name="needed_skills")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.title))
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at']


class FavoriteJob(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'job')  # Ensure a job can be favorited only once per user


class Applicant(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applicants")
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True, null=True)
    status = models.SmallIntegerField(default=1)

    class Meta:
        ordering = ["id"]
        unique_together = ["user", "job"]

    @property
    def get_status(self):
        if self.status == 1:
            return "Pending"
        elif self.status == 2:
            return "Accepted"
        else:
            return "Rejected"

jobsPy/jobs/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, View, DeleteView
from rest_framework import permissions
from rest_framework.generics import ListAPIView

from jobsPy.company.models import CompanyProfile
from jobsPy.core.accounts_mixins import CompanyRoleRequiredMixin, JobByCompanyMixin, CompanyProfileActivationMixin, \
    ApplicantCompanyMixin
from jobsPy.core.decorators import job_seeker_activated_required
from jobsPy.jobs.forms import CreateJobForms, EditeJobForm, ApplyForJobForms, ChangeStatusForm
from jobsPy.jobs.models import Job, Category, Applicant, FavoriteJob
from jobsPy.jobs.serializers import JobSerializer
from jobsPy.main.models import Seniority, CompanySubscription

userModel = get_user_model()

class JobCreateView(LoginRequiredMixin, CompanyRoleRequiredMixin, CompanyProfileActivationMixin, CreateView):
    template_name = "jobs/create_job.html"
    form_class = CreateJobForms
    extra_context = {"title": "Post New Job"}
    success_url = reverse_lazy("company-dashboard")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(JobCreateView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class AllJobsView(ListView):
    model = Job
    template_name = "jobs/jobs_list.html"
    paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        seniority_filter = self.request.GET.get('seniority')
        queryset = Job.objects.filter(is_published=True)

        if seniority_filter:
            queryset = queryset.filter(seniority__name=seniority_filter)

        if query:
            # If a search query is present, filter the queryset by job title
            queryset = queryset.filter(title__icontains=query)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.all()
        context["seniorities"] = Seniority.objects.all()
        context['search_query'] = self.request.GET.get('q', '')
        return context


class JobDetails(DetailView):
    template_name = "jobs/job-details.html"
    model = Job

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_anonymous:
            return context

        job = context['object']
        context["already_in_favourite"] = FavoriteJob.objects.filter(user=self.request.user, job=job).exists()
        context["already_apply"] = Applicant.objects.filter(user=self.request.user, job=job).exists()
        context["status"] = Applicant.objects.filter(user=self.request.user, job=job)
        # Access the CompanyProfile through the user's ID
        company_profile = CompanyProfile.objects.get(user_id=job.user_id)
        context['company'] = company_profile
        return context


class EditJob(LoginRequiredMixin, CompanyRoleRequiredMixin, JobByCompanyMixin, UpdateView):
    model = Job
    form_class = EditeJobForm
    template_name = "jobs/edit-job.html"

    def get_success_url(self):
        return reverse_lazy("job_details",  kwargs={"pk": self.object.pk})


# class AddToFavoritesView(LoginRequiredMixin, View):
#     # @login_required
#     def post(self, request, pk):
#         job = get_object_or_404(Job, id=pk)
#
#         # Check if the job is already in favorites for the current user
#         if FavoriteJob.objects.filter(user=request.user, job=job).exists():
#             # Job is already in favorites, handle this case (e.g., display a message)
#             pass
#         else:
#             # Job is not in favorites, add it to the favorites
#             FavoriteJob.objects.create(user=request.user, job=job)
#
#         return redirect('job_details', pk)

# class AddToFavoritesView(LoginRequiredMixin, CreateView):
#     model = FavoriteJob
#     template_name = 'add_to_favorites.html'
#     fields = []
#
#     def form_valid(self, form):
#         job = get_object_or_404(Job, pk=self.kwargs['pk'])
#         form.instance.user = self.request.user
#         form.instance.job = job
#         return super().form_valid(form)
#
#     def get_success_url(self):
#         job = get_object_or_404(Job, pk=self.kwargs['pk'])
#         return reverse_lazy("job_details",  kwargs={"pk": job.pk})


class RemoveFromFavoritesView(LoginRequiredMixin, View):

    def post(self, request, pk):
        job = get_object_or_404(Job, id=pk)

        # Check if the job is in favorites for the current user
        favorite_job = FavoriteJob.objects.filter(user=request.user, job=job).first()

        if favorite_job:
            # Job is in favorites, remove it
            favorite_job.delete()

        return redirect('job_details', pk)


@login_required
@job_seeker_activated_required
def apply_for_job(request, pk):
    job = get_object_or_404(Job, id=pk)

    if request.user.is_authenticated and request.user.role == 'jobseeker':

        # Check if the user has already applied for this job
        if not Applicant.objects.filter(user=request.user, job=job).exists():
            # Create an Applicant instance and save it to the database
            Applicant.objects.create(user=request.user, job=job)
            # You can also use a form to save additional data if needed
            form = ApplyForJobForms(request.POST or None)
            if form.is_valid():
                applicant = form.save(commit=False)
                applicant.user = request.user
                applicant.job = job
                applicant.save()

    return redirect('job_details', pk=job.id)


@login_required
def add_to_favorites(request, pk):
    if request.user.role != 'jobseeker':
        return redirect('job_details', pk=pk)

    job = get_object_or_404(Job, pk=pk)

    # Check if the job is not already in favorites
    if not FavoriteJob.objects.filter(user=request.user, job=job).exists():
        FavoriteJob.objects.create(user=request.user, job=job)

    return redirect('job_details', pk=pk)


class ChangeStatus(LoginRequiredMixin, CompanyRoleRequiredMixin, ApplicantCompanyMixin, UpdateView):
    model = Applicant
    template_name = "jobs/change_status.html"
    form_class = ChangeStatusForm

    def get_success_url(self):
        return reverse_lazy("applicant_list", kwargs={"pk": self.object.job_id})


class DeleteJob(LoginRequiredMixin, CompanyRoleRequiredMixin, JobByCompanyMixin, DeleteView):
    model = Job
    template_name = "company/delete_job.html"
    success_url = reverse_lazy('company-dashboard')


@login_required
def subscribe_to_company(request, pk):
    company = get_object_or_404(userModel, pk=pk)
    is_subscribed = CompanySubscription.objects.filter(
        job_seeker=request.user,
        company=company
    ).exists()
    if request.method == 'POST':
        if is_subscribed:
            CompanySubscription.objects.filter(
                job_seeker=request.user,
                company=company
            ).delete()
        else:
            CompanySubscription.objects.create(
                job_seeker=request.user,
                company=company
            )
    return redirect('company-details', pk=pk)


class AllJobsViewApi(ListAPIView):
    serializer_class = JobSerializer
    pagination_class = None  # Disable pagination
    permission_classes = permissions.AllowAny,

    def get_queryset(self):
        queryset = Job.objects.filter(is_published=True)
        query = self.request.GET.get('q')
        seniority_filter = self.request.GET.get('seniority')

        if query:
            queryset = queryset.filter(title__icontains=query)

        if seniority_filter:
            queryset = queryset.filter(seniority=seniority_filter)

        return queryset

templates/jobs/category_slide.html
                        <div class="widget categories-widget">

                            <h5 class="widget-title"><span>Categories</span></h5>
                            <ul class="custom">
                                {% for cat in category %}
                                <li>
                                    <a href="{% url 'jobs_category' cat.slug %}">{{ cat.name }}<span>{{ cat.job_set.all|length }}</span></a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>

templates/jobs/change_status.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Change Status for {{ object.user.jobseeker.first_name  }} {{ object.user.jobseeker.last_name  }}{% endblock %}
{% block main_content %}
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Change status for {{ object.user.jobseeker.first_name  }} {{ object.user.jobseeker.last_name  }}</h1>
                        <p>Business plan draws on a wide range of knowledge from different business<br> disciplines.
                            Business draws on a wide range of different business .</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Change Status</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Main Content Start -->
    <div class="change-password section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    <!-- Start Main Content -->

                    {% include "company/company-menu.html" %}

                    <!-- End Main Content -->
                    <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Edit {{ object.user.jobseeker.first_name  }} {{ object.user.jobseeker.last_name  }} status</h3>
                        
                            <form method="post" action="{% url 'change-status' object.pk %}" enctype="multipart/form-data">
                                <div class="row">

                                                     {% for field in form %}
                    <div class="form-group">
                    <div>{{ field.label_tag }}</div>
                    {{ field }}
                     </div>
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}

                {% endfor %}




                                    {% csrf_token %}
                                    <div class="col-lg-12">
                                        <div class="button">
                                            <button class="btn">Change</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content end -->

 {% endblock %}

templates/jobs/create_job.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create Jobs - JobsPy {% endblock %}
{% block main_content %}
    
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Create Job Offer</h1>
                        <p>Create your own job offer in minutes <br> with
                            JobsPy</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url "index" %}">Home</a></li>
                        <li><a href="{% url "company-dashboard" %}">Dashboard</a></li>
                        <li>Create Job</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Main Content Start -->
    <div class="change-password section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    <!-- Start Main Content -->

                    {% include "company/company-menu.html" %}
                    <!-- End Main Content -->
                    <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Create Job</h3>
                            <p>Here you can post new Job.</p>
                            {% if form.errors %}
                            <div class="alert alert-danger">
                            {{ form.errors }}
                            </div>
                            {% endif %}
                            <form method="post" action="{% url 'create_job' %}" enctype="multipart/form-data">
                                <div class="row">
                                    {{ form.media }}
                     {% for field in form %}
                    <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                     </div>
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}

                {% endfor %}

                                    {% csrf_token %}
                                    <div class="col-lg-12">
                                        <div class="button">
                                            <button class="btn">Post Job</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content end -->

 {% endblock %}

templates/jobs/edit-job.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Edit Job {{ object.title }}{% endblock %}
{% block main_content %}
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Edit Job {{ object.title }}</h1>
                        <p>Business plan draws on a wide range of knowledge from different business<br> disciplines.
                            Business draws on a wide range of different business .</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url "company-dashboard" %}">Dashboard</a></li>
                        <li>Edit Job</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Main Content Start -->
    <div class="change-password section">
        <div class="container">
            <div class="alerts-inner">
                <div class="row">
                    <!-- Start Main Content -->

                    {% include "company/company-menu.html" %}

                    <!-- End Main Content -->
                    <div class="col-lg-8">
                        <div class="password-content">
                            <h3>Edit Job</h3>
                            <p>Here you can edit Job.</p>
                            <form method="post" action="{% url 'edit_job' object.pk %}" enctype="multipart/form-data">
                                <div class="row">
                                    {{ form.media }}
                                {{ form }}




                                    {% csrf_token %}
                                    <div class="col-lg-12">
                                        <div class="button">
                                            <button class="btn">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main Content end -->

 {% endblock %}

templates/jobs/jobs_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Browse all Jobs -  JobsPy {% endblock %}
{% block main_content %}
    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs overlay">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Job offers</h1>
                        <p>Job offers from leading companies <br>
                           New Company jobs added daily...</p>
                    </div>
                    <ul class="breadcrumb-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li>Job offers</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

    <!-- Start Blog Singel Area -->
    <section class="section blog-single">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">

                          {% for job in job_list %}
                        <div class="single-job">
{#                        <div class="feature-job-list">Featured</div>#}
                            <div class="job-image-list">
            {% if job.user.company.image %}
                                <img src="{{ job.user.company.image.url }}" alt="#">
                                {% else %}
                 <img src="{% static 'images/jobs/category-2.jpg' %}" alt="{{ company.name }} Image">
                                {% endif %}
{#                               <p> <a href="{% url 'company-details' job.user.company.pk %}">{{ job.user.company.name }}</a></p>#}

                            </div>
                            <div class="job-content">
                                <h4 style="padding-right: 0px"><a href="{% url 'job_details' job.pk %}">{{ job.title }}</a></h4>
                                <div class="truncate-overflow-jobs">
                                <p>{{ job.description|safe|default_if_none:"nothing" }}</p>
                                </div>
                                <ul>
                                    <li><i class="lni lni-euro"></i> {{ job.salary }} </li>
                                    <li><i class="lni lni-map-marker"></i> {{ job.location }}</li>
                                    <li><i class="lni lni-calendar"></i> {{ job.seniority }}</li>
                                    <li><i class="lni lni-timer"></i> {{ job.job_type }}</li>

        

                                </ul>

                                <ul>
                                                            {% for skill in job.needed_skills.all %}
                                                <li><span>{{ skill.name }}</span></li>
                                        {% endfor %}
                            </ul>
                            </div>
                            <div class="job-button2">
{#                                <ul>#}
{#                                    <li><a href="{% url 'apply_for_job' job.pk %}">Apply</a></li>#}
                                    <a class="company-link" href="{% url 'company-details' job.user.company.pk %}"><span>Company : {{ job.user.company.name }}</span></a></li>
{#                                </ul>#}
                            </div>
                        </div>
                    {% endfor %}
{% if is_paginated %}
    <div class="pagination left pagination-md-center">
        <ul class="pagination-list">
            {% if page_obj.has_previous %}

                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="lni lni-arrow-left"></i></a></li>
                            {% else %}
                <li><span><i class="lni lni-arrow-left"></i></span></li>
      
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                <li {% if page_obj.number == num %}class="active"{% endif %}><a href="?page={{ num }}">{{ num }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.paginator.num_pages }}"><i class="lni lni-arrow-right"></i></a></li>
            {% else %}
                <li><span><i class="lni lni-arrow-right"></i></span></li>
            {% endif %}
        </ul>
    </div>
{% endif %}
                </div>
                <aside class="col-lg-4 col-md-12 col-12">
                    <div class="sidebar">
                            <div class="widget search-widget">
{#                            <h5 class="widget-title"><span>Search This Site</span></h5>#}
                             <form method="get" action="{% url 'all-jobs' %}">
                                <input type="text" name="q" placeholder="Search by job title">
                                <button type="submit"><i class="lni lni-search-alt"></i></button>
                            </form>
                             </div>

                                 <div class="widget search-widget">

                               <form method="GET" action="{% url 'all-jobs' %}">
                                    <select style="max-width: 70%" class="form-select form-select-sm"  name="seniority">
                                    <option value="">All</option>
                                    {% for seniority in seniorities %}
                                        <option value="{{ seniority.name }}">{{ seniority.name }}</option>
                                    {% endfor %}
                                    </select>
                               <div>
                                    <button  type="submit">Filter</button>
                               </div>
                                 </form>
                             </div>

                        {% include "jobs/category_slide.html" %}


                        <div class="widget popular-feeds">
                            <h5 class="widget-title"><span>Latest Blog Posts with DRF</span></h5>
                            <div class="popular-feed-loop">
                            </div>
                        </div>

                        <div class="widget popular-tag-widget">
                            <h5 class="widget-title"><span>Popular Tags</span></h5>
                            <div class="tags">
                                <a href="#">ToDo</a>
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </section>
    <script src="{% static '/js/blog/popular_feeds.js' %}"></script>
{% endblock %}